---

openshift_cluster_content:
- object: projectrequest
  content:
  - name: "demo-pipeline"
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../templates/projectrequest/pipeline.params"
    template_action: create
  - name: "demo-dev"
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../templates/projectrequest/dev.params"
    template_action: create
  - name: "demo-test"
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../templates/projectrequest/test.params"
    template_action: create
  - name: "demo-prod"
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/../templates/projectrequest/prod.params"
    template_action: create
- object: ci-cd-builds
  content:
  - name: "jenkins-s2i"
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v3.7.4/openshift-templates/jenkins-s2i-build/template.yml"
    params: "{{ inventory_dir }}/../templates/build/jenkins.params"
    namespace: "demo-pipeline"
- object: builds
  content:
  - name: "demo-pipeline"
    template: "{{ inventory_dir }}/../templates/build/template-pipeline.yml"
    params: "{{ inventory_dir }}/../templates/build/pipeline.params"
    namespace: "demo-pipeline"
  - name: "demo-build"
    template: "{{ inventory_dir }}/../templates/build/template-build.yml"
    params: "{{ inventory_dir }}/../templates/build/build.params"
    namespace: "demo-pipeline"
- object: deployments
  content:
  - name: "custom-jenkins"
    template: "{{ inventory_dir }}/../templates/deploy/jenkins-template.yml"
    params: "{{ inventory_dir }}/../templates/deploy/jenkins.params"
    namespace: "demo-pipeline"
  - name: "demo-dev"
    template: "{{ inventory_dir }}/../templates/deploy/template.yml"
    params: "{{ inventory_dir }}/../templates/deploy/dev.params"
    namespace: "demo-dev"
  - name: "demo-test"
    template: "{{ inventory_dir }}/../templates/deploy/template.yml"
    params: "{{ inventory_dir }}/../templates/deploy/test.params"
    namespace: "demo-test"
  - name: "demo-prod"
    template: "{{ inventory_dir }}/../templates/deploy/template.yml"
    params: "{{ inventory_dir }}/../templates/deploy/prod.params"
    namespace: "demo-prod"
